### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Nikita-Zaitsev-ML** [Alexioi/toxin-hotel#5]
нарушается [CSS 4.4](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.4)

![image](https://user-images.githubusercontent.com/104826556/197833721-5c6ed6bc-4a06-497c-949c-b5b9a4726a85.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Вместо мутации лучше пересоздавать: [JS 8.3](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#8.3)

![image](https://user-images.githubusercontent.com/104826556/197834306-5bb54bbe-b6a1-4fe0-a462-6e2703a3ad86.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Вместо доступа по индексу, следует использовать циклы или деструктуризацию: это повышает читабельность. А еще помнить что элемент может оказаться `undefined` - с доступом по индексу и при деструктуризации надо быть поаккуратнее: например если значения нет, то блок все равно будет добавлен в дерево с дефолтными параметрами, что не является ожидаемым поведением

[JS 2.6](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.6)

![image](https://user-images.githubusercontent.com/104826556/197835915-7f91dfe6-5e06-48d1-a16c-8e8cc324b3ed.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Нарушен порядок импортов, [JS 1.17](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.17)

![image](https://user-images.githubusercontent.com/104826556/197848504-13665c26-847e-4f53-a3a6-0b6ffc132e72.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Порядок методов, [JS 8.5](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#8.5)

![image](https://user-images.githubusercontent.com/104826556/197848794-e1cd868d-66e8-43dd-a93e-a8ab4a254b66.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Строго говоря нарушается [airbnb 3.5](https://github.com/airbnb/javascript#objects--grouped-shorthand). Предлагаю следующее: применять описанные подход, но для "свойств-значений" и "свойств-функций" по отдельности - учитывать что shorthand должны быть выше, но "свойства-функции" всегда размещать после любых "свойств-значений". В данном случае `dataSource` разместить под `callback` или `nextText`

![image](https://user-images.githubusercontent.com/104826556/205585205-4d859cd9-94c3-47f1-9438-6c21c02be80a.png)

**Comment by Nikita-Zaitsev-ML** [comment]
проблема уже встречалась [тут](https://github.com/Alexioi/toxin-hotel/issues/2#issuecomment-1336828288). Дополнительно поясню: деструктуризация лучше доступа по индексу т.к. даёт описательное имя значению что снижает когнитивную нагрузку при чтении кода(хотя проверять на `undefined` по-прежнему надо т.к. это делает программу более стабильной). Циклы же просто сильно упрощают жизнь)

[JS 2.6](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.6)

![image](https://user-images.githubusercontent.com/104826556/207874300-c5ab5808-8686-47d9-821d-5d9b10f62899.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[airbnb 15.3](https://github.com/airbnb/javascript#comparison--shortcuts)

![image](https://user-images.githubusercontent.com/104826556/207875560-99b7c753-1954-4052-894c-b5392d895826.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[airbnb 3.5](https://github.com/airbnb/javascript#objects--grouped-shorthand)

![image](https://user-images.githubusercontent.com/104826556/210137032-5af81e71-3e10-414a-855f-7a4b2d709f5d.png)

**Comment by Nikita-Zaitsev-ML** [comment]
`bind` стоит выполнять  `bind` лучше делать в конструкторе т.к. это позволит когда понадобится использовать `removeEventListener`.

[JS 1.13](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.13)

[пример](https://reactjs.org/docs/faq-functions.html)

![image](https://user-images.githubusercontent.com/104826556/210137186-9ce361fe-790f-4652-b712-ef236118bba9.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[JS 2.4](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.4)

![image](https://user-images.githubusercontent.com/104826556/210137346-18b9d1f9-2f39-4922-9a88-b519034df5e9.png)

**Comment by Nikita-Zaitsev-ML** [comment]
мутаций стоит избегать: тут подойдет `reduce`

[JS 1.15](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.15)

![image](https://user-images.githubusercontent.com/104826556/210137464-3c5aca4d-5000-4a06-bf3a-b832b9e7d5b2.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[airbnb 5.3](https://github.com/airbnb/javascript#destructuring--object-over-array)

![image](https://user-images.githubusercontent.com/104826556/210138143-889a39ce-23ae-4025-97b5-cf9100052ea4.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[airbnb 9.3](https://github.com/airbnb/javascript#constructors--chaining)

**Comment by Nikita-Zaitsev-ML** [comment]
Конкретно тут можно использовать const и тернарный оператор для назначения значения по условию и обрати внимание на стандарт(хотя в идеале вообще `let` не использовать):

[airbnb 13.3](https://github.com/airbnb/javascript#variables--const-let-group)

![image](https://user-images.githubusercontent.com/104826556/210138322-753be945-fcc2-4f73-b7ae-4db1e62d9342.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[JS 5.2](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#5.2)
[JS 1.25](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.25)

![image](https://user-images.githubusercontent.com/104826556/210140179-5f8e5f24-eb4c-4903-8fe7-fdbc8f743aec.png)

хранить значение состояния в `dataset` небезопасно: можно изменить значение через панель разработки. Вывод предназначен для вывода данных. Источников истины должно быть внутреннее состояние

![image](https://user-images.githubusercontent.com/104826556/210138578-5ec0aa83-d9a7-458c-955d-9074485c02e9.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[airbnb 15.3](https://github.com/airbnb/javascript#comparison--shortcuts)

[JS 1.10](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.10)

![image](https://user-images.githubusercontent.com/104826556/210138672-f1c8bc63-56cc-4cfc-a463-56977a0bfedd.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[JS 3.3](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#3.3)

![image](https://user-images.githubusercontent.com/104826556/210138909-a906b5c7-60e5-484e-bd0e-2892b8270654.png)

**Comment by Nikita-Zaitsev-ML** [comment]
не статичные методы лучше по максимуму выносить из класса в отдельные функции(вместо this стараться использовать аргументы), функции оставлять можно в файле класса): сейчас каждый инстанс будет содержать отдельную копию каждой функции, что лишний раз засоряет память

**Comment by Nikita-Zaitsev-ML** [comment]
Стоит выносить в константы: полезно при смене значения - можно изменить в одном месте + становится яснее откуда взялось значение + для чего-то типа путей ниже шанс сделать описку
P.S.: с typescript не так актуально
P.S.S.: значение больше про данные, недостаточно абстрактное как для компонента

[JS 1.16](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.16)

![image](https://user-images.githubusercontent.com/104826556/210139242-8e10228e-495b-4d5f-8dbb-8bd9ea39fc8c.png)

**Comment by Nikita-Zaitsev-ML** [comment]
должны быть разделены пустой строкой

[JS 1.17](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.17)

неверный порядок

![image](https://user-images.githubusercontent.com/104826556/210139322-0b30f08d-041b-4bf6-a8de-aeb14bf1e8fa.png)


![image](https://user-images.githubusercontent.com/104826556/210139307-754e7198-6207-410e-bbed-fbfc8f4bdc0f.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Стоит проработать названия:

[JS 2.1](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.1)
[JS 2.7](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.7)

![image](https://user-images.githubusercontent.com/104826556/210139667-3013fd7d-2d6d-44e8-b678-656fa9cd9750.png)
![image](https://user-images.githubusercontent.com/104826556/210139706-2193d9b9-22ba-4c0e-8b06-25986ce177e7.png)
![image](https://user-images.githubusercontent.com/104826556/210139720-cc761e9b-56cd-4f23-a819-5925d8fea338.png)
![image](https://user-images.githubusercontent.com/104826556/210139806-bf8c1173-7f0c-4bc1-aacc-1fd6937f85b4.png)

**Comment by Nikita-Zaitsev-ML** [comment]
[JS 5.2](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#5.2)
[JS 1.25](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.25)

![image](https://user-images.githubusercontent.com/104826556/210140087-f25b4045-dfcd-466a-a8c6-34d5a42fe855.png)

**Comment by Nikita-Zaitsev-ML** [comment]
> проблема уже встречалась [тут](https://github.com/Alexioi/toxin-hotel/issues/2#issuecomment-1336828288). Дополнительно поясню: деструктуризация лучше доступа по индексу т.к. даёт описательное имя значению что снижает когнитивную нагрузку при чтении кода(хотя проверять на `undefined` по-прежнему надо т.к. это делает программу более стабильной). Циклы же просто сильно упрощают жизнь)
> 
> [JS 2.6](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.6)
> 
> ![image](https://user-images.githubusercontent.com/104826556/207874300-c5ab5808-8686-47d9-821d-5d9b10f62899.png)

тут еще можно подшаманить 
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/4b1fc48a-1239-4507-9590-ec3b211c95a0)

**Comment by Nikita-Zaitsev-ML** [comment]
> [airbnb 3.5](https://github.com/airbnb/javascript#objects--grouped-shorthand)
> 
> ![image](https://user-images.githubusercontent.com/104826556/210137032-5af81e71-3e10-414a-855f-7a4b2d709f5d.png)

не исправлено

**Comment by Nikita-Zaitsev-ML** [comment]
> мутаций стоит избегать: тут подойдет `reduce`
> 
> [JS 1.15](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.15)
> 
> ![image](https://user-images.githubusercontent.com/104826556/210137464-3c5aca4d-5000-4a06-bf3a-b832b9e7d5b2.png)

остались мутации:
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/1141b916-a883-4c89-9abc-e9b2f9a64358)

**Comment by Nikita-Zaitsev-ML** [comment]
> [airbnb 9.3](https://github.com/airbnb/javascript#constructors--chaining)

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/c35ab633-db5d-47a2-a062-c078befe2bfc)

**Comment by Nikita-Zaitsev-ML** [comment]
`isFocus` -> `isFocused`

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/5ec21e3a-30e8-40ed-980c-f1b197cdf469)

**Comment by Nikita-Zaitsev-ML** [comment]
> [airbnb 15.3](https://github.com/airbnb/javascript#comparison--shortcuts)
> 
> [JS 1.10](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.10)
> 
> ![image](https://user-images.githubusercontent.com/104826556/210138672-f1c8bc63-56cc-4cfc-a463-56977a0bfedd.png)

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/0c0c5a54-7d5e-4391-9548-12cf92d605a4)

**Comment by Nikita-Zaitsev-ML** [comment]
> не статичные методы лучше по максимуму выносить из класса в отдельные функции(вместо this стараться использовать аргументы), функции оставлять можно в файле класса): сейчас каждый инстанс будет содержать отдельную копию каждой функции, что лишний раз засоряет память

эти 2 метода можно также вынести в отдельные функции чтобы не выделять под них память при инстанцировании: можно передавать аргументы и возвращать обновлённые значения. Аналогичная проблема встречается и в других файлах
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/fc4d4bc0-caec-4c89-9995-e6f6a1edad6a)

**Comment by Nikita-Zaitsev-ML** [comment]
> Стоит проработать названия:
> 
> [JS 2.1](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.1) [JS 2.7](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#2.7)
> 
> ![image](https://user-images.githubusercontent.com/104826556/210139667-3013fd7d-2d6d-44e8-b678-656fa9cd9750.png) ![image](https://user-images.githubusercontent.com/104826556/210139706-2193d9b9-22ba-4c0e-8b06-25986ce177e7.png) ![image](https://user-images.githubusercontent.com/104826556/210139720-cc761e9b-56cd-4f23-a819-5925d8fea338.png) ![image](https://user-images.githubusercontent.com/104826556/210139806-bf8c1173-7f0c-4bc1-aacc-1fd6937f85b4.png)

однотипные по функциональности методы лучше называть одинаково: упрощается навигация и снижается когнитивная нагрузка
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/0765e63b-31c7-4f0f-9d6d-fb65276d593e)

get void? - думаю стоит использовать приставку `emit` в данном случае. Функции с приставкой `get` без возвращаемого значения встречаются во многих местах.
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/2c247b2f-9b8c-43d2-97fe-fed093856276)

Функции не должны содержать в названии несколько действий. В данном случае лучше использовать название `emitUpdateCounters`
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/62911a77-2b4d-4f11-b075-68f4d99d1299)

**Comment by Nikita-Zaitsev-ML** [comment]
Стоит привести к одному виду: или глагол или существительное везде

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/cc169d07-2824-461e-9b49-fc96a61bb9aa)

**Comment by Nikita-Zaitsev-ML** [comment]
лучше добавить index файл в каждую из папок, в котором экспортировать нужный API(в данном случае скорее всего только default экспорт класса)

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/96956cc7-63fe-4db6-8011-f48b75ff92bc)

**Comment by Nikita-Zaitsev-ML** [comment]
А для чего тут `never`?

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/4b613c8f-9bf3-489d-ab57-8ed81474c9d3)

**Comment by Nikita-Zaitsev-ML** [comment]
`any` разрешен только в случае если совсем никак не получается затипизировать, при этом необходимо написать подробный комментарий, описывающий причину использования.

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/a022b931-38dd-48cd-a212-00478e2cb0d6)

**Comment by Nikita-Zaitsev-ML** [comment]
лишнее приведение типа: надо изменить тип аргумента, принимаемого конструктором

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/397b8e6b-7b12-4040-a453-aab7e2541f2b)

**Comment by Nikita-Zaitsev-ML** [comment]
а если `value === 0` ?

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/5d268f7e-7736-457e-9b6a-e6fcfe99b83f)

**Comment by Nikita-Zaitsev-ML** [comment]
вместо вложенных условий лучше использовать предпроверки, в данном случае: `if (this.counter === null) { return }`

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/2cfc497e-cb10-46c1-89ac-e708381f5a77)

**Comment by Nikita-Zaitsev-ML** [comment]
правила добавлены не просто так: стоит разобраться для чего оно вообще нужно. Если есть абсолютная уверенность что правило вредное - лучше отключать на уровне конфига(в данном случае не этот случай)

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/951ac734-6aee-40e5-9da5-f9f6002de770)

**Comment by Nikita-Zaitsev-ML** [comment]
`@ts-ignore` запрещен

В рамках учебных проектов запрещено использовать приведение типов.

P.S.: вместо `<Type>` предпочтительное использовать `as Type`: он популярнее. 

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/dde2a300-c07c-45da-9072-271d781f9bca)

**Comment by Alexioi** [comment]
> а если `value === 0` ?
> 
> ![image](https://user-images.githubusercontent.com/104826556/248810483-5d268f7e-7736-457e-9b6a-e6fcfe99b83f.png)

поле класса по умолчанию имеет значение 0, по этому при инициализации класса поле this.value изменяется только при значения больше нуля
![image](https://github.com/Alexioi/toxin-hotel/assets/38693355/0cb20909-71e5-4065-bcfa-64c3043a5257)

**Comment by Alexioi** [comment]
> вместо вложенных условий лучше использовать предпроверки, в данном случае: `if (this.counter === null) { return }`
> 
> ![image](https://user-images.githubusercontent.com/104826556/248810619-2cfc497e-cb10-46c1-89ac-e708381f5a77.png)
к сожалению это не всегда работает, например в данной ситуации ts теряет тип 
![image](https://github.com/Alexioi/toxin-hotel/assets/38693355/6e3efae3-db7c-4198-9cf1-68d0415a448f)

**Comment by Nikita-Zaitsev-ML** [comment]
не должно быть неявного импорта

![Code_k1GOPPGcA0](https://github.com/Alexioi/toxin-hotel/assets/104826556/8f79cecb-cef3-4473-947f-799221ebe517)

думаю можно отказаться от jq на данном проекте: лучше не смешивать подходы(js+es6), а пользоваться одним - это сделает код более шаблонным, что упростит работу с ним.

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/5aa4db3b-4e4e-4cee-9122-314a5755e91f)

**Comment by Nikita-Zaitsev-ML** [comment]
лучше вынести в тип с именем
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/2d8f1d0d-3b64-428b-9f85-34c4599c9fa2)

**Comment by Nikita-Zaitsev-ML** [comment]
События следует делать объектами с полями. [airbnb 25.1](https://github.com/airbnb/javascript#events--hash)

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/cf16f953-2399-4926-a648-4370c334610a)

**Comment by Nikita-Zaitsev-ML** [comment]
https://github.com/Alexioi/toxin-hotel/issues/5#issuecomment-1607448722

аналогично:

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/d4fc76f3-b30b-431a-a9d6-49690effae0a)

**Comment by Nikita-Zaitsev-ML** [comment]
Еще остались необоснованные приведения:

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/8545c4d3-95fe-445c-9e99-6f547306d343)

**Comment by Nikita-Zaitsev-ML** [comment]
https://github.com/Alexioi/toxin-hotel/issues/5#issuecomment-1607458306

следует делать структуру кода максимально плоской: это позволит не держать в голове цепочку предыдущих условий и упростит навигацию по коду
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/3ddd9e09-5aa4-4a2e-b94e-51d0dd9a788a)

**Comment by Nikita-Zaitsev-ML** [comment]
return this?

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/a65402b4-7c58-4f79-b2c1-3d0c3e958bd2)

**Comment by Nikita-Zaitsev-ML** [comment]
https://github.com/Alexioi/toxin-hotel/issues/5#issuecomment-1616638417

достаточно неочевидно: лучше назначать в одном месте.
Сейчас в итоге так и сделано:
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/d27cb895-dcd6-4e8a-8467-f49e5d1a3e23)

**Comment by Nikita-Zaitsev-ML** [comment]
лучше во всех местах добавить `index.ts` файл с реекспортом чтобы можно было писать `import { Calendar, cssSelectors} from ./scripts`: 
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/c50f08fd-0a69-4837-8522-2f3261d9cbfb)

**Comment by Nikita-Zaitsev-ML** [comment]
В таких случаях лучше экспортировать `HTMLInputElementWithPlugin` из `@components/text-field/index.ts` и импортировать весь компонент: `import * as TextField from '@components/text-field';`(или использовать default экспорт и импорт как у тебя в других местах, но мы предпочитаем не использовать экспорт по уполчанию): думай о компоненте как о модуле, `index` файл которого предоставляет некий API, которым могут пользоваться другие компоненты/другие участки программы - не стоит другим участкам программы лезть внутрь компонента. Дополнительным преимуществом будет namespac-инг для имен

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/cfe9b1bc-8d53-4be4-b654-b955fa4d47dc)

**Comment by Nikita-Zaitsev-ML** [comment]
достаточно странно что `constants` по умолчанию экспортирует не `constans`: следует отказаться от экспорта по умолчанию(в идеале вообще его никогда не использовать т.к. лучше везде экспортировать по единому имени и импортировать только нужное). Альтернативой может быть переименование файла т.к. это шаблонный файл. Но имя constants используется чаще и может содержать и другие константы, которые могут потребоваться в будущем(нежелательно иметь несколько файлов со сходным функционалом в одном месте)

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/06cbc446-9487-4d71-97ee-d820ff7e7035)

аналогичная проблема: можно импортировать просто `import * as TS from '../../types'`
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/7022eec9-cfe9-4834-95b6-45b27e691d69)

**Comment by Nikita-Zaitsev-ML** [comment]
подобное лучше объединять в одно поле, в данном случае: `dom` - это упростит навигацию и позволит назначать значение в одну переменную при инициализации

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/737516d5-3004-4dd0-b7a2-4c01c0626bb2)

**Comment by Nikita-Zaitsev-ML** [comment]
Для обработчиков нет необходимости возвращать `this`: они не вызываются в цепочке вызовов.

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/1cc1bda9-aa74-4c23-a9c6-da9cecafa367)

**Comment by Nikita-Zaitsev-ML** [comment]
можно дать более осмысленные имена переменным кнопок

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/20c3af71-36d2-4434-bb05-fae86d26ed9e)

**Comment by Nikita-Zaitsev-ML** [comment]
`isJQueryWithAirDatepicker` -> `isElementWithAirDatepicker`

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/8e40ef39-bb2a-4a05-8568-0e663849f05b)

**Comment by Nikita-Zaitsev-ML** [comment]
имя метода не соответствует имени возвращаемого типа

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/eb260e83-6b41-4068-ac0c-38c3fb1200a9)

**Comment by Nikita-Zaitsev-ML** [comment]
состояния лучше проверять не по наличию селектора в DOM, а по полю инстанса класса: должна быть одна точка правды

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/4a41e2c7-fc29-4db9-bd45-3861333537fb)

**Comment by Nikita-Zaitsev-ML** [comment]
Для аргументов колбеков методов массива удобно использовать сокращения, например `someArray.reduce((acc, x)=>...)`: сокращения уместны потому что из имени массива понятно что перебираем и мы получаем более шаблонный(читай простой для понимания) код.
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/34bbbb7d-f942-459e-98ae-53d988eaa184)

**Comment by Nikita-Zaitsev-ML** [comment]
должен использоваться префикс `js-`
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/8dfb944a-a9c9-424d-b19b-812463793ddf)

**Comment by Nikita-Zaitsev-ML** [comment]
А зачем каждый раз создавать и передавать эмиттер, когда можно наследоваться от него? Лучше не шарить объект эмиттера, а иметь методы у самих `View`, `Model`

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/a4a76a94-7eb0-45bf-84da-4404421a51bb)

**Comment by Nikita-Zaitsev-ML** [comment]
не думаю что `emitValue` должен быть публичным: для твоих целей лучше использовать отдельные специфичные методы

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/56740042-8bd1-497f-996b-cb2fe39c3d1a)

**Comment by Nikita-Zaitsev-ML** [comment]
лучше из метода `init` возвращать проинициализированное значение, которое в конструкторе назначать полю: это будет более функциональный стиль, без мутаций внутри метода

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/921b96e8-2357-4962-82d4-146c6cac4aab)

**Comment by Nikita-Zaitsev-ML** [comment]
handler-ы лучше выносить

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/0c41e639-7d5d-4c37-ae64-39ca9bfc3371)

**Comment by Nikita-Zaitsev-ML** [comment]
вместо дублирования типов лучше использовать type alias-ы для handler-ов: `const const someHandler: EventNameCallback = (...) => {...}`

**Comment by Nikita-Zaitsev-ML** [comment]
`index` необязательно указывать в пути

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/f725cbbd-0d96-4142-b3ca-f40e2f89c7be)

**Comment by Nikita-Zaitsev-ML** [comment]
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/cfae297f-0f4a-4dc8-9766-1f9dfd203440)

**Comment by Nikita-Zaitsev-ML** [comment]
стоит отсортировать 
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/243da3ce-036e-471d-916a-893d5b9c3405)

**Comment by Nikita-Zaitsev-ML** [comment]
вместо атрибутов следует использовать свойства

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/f5deb8f2-90db-4226-b9a9-917f374875df)

**Comment by Nikita-Zaitsev-ML** [comment]
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/f60fe606-271b-4e25-9253-336093f6d06b)

**Comment by Nikita-Zaitsev-ML** [comment]
get?

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/86c4e5fc-381f-4c50-85c5-6c131eb0ebf5)

**Comment by Nikita-Zaitsev-ML** [comment]
`isValidDate` -> `isDateValid`
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/7973f04a-3cd1-4726-a386-5924fbf90b61)

**Comment by Nikita-Zaitsev-ML** [comment]
вместо методов регулярных выражений лучше использовать методы строк т.к. они не мутируют `regexp.lastIndex` и не результат не зависит от него

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/1e92f3db-58aa-4396-9699-2cec5c4ee268)

**Comment by Nikita-Zaitsev-ML** [comment]
AndMonth?

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/2f647e1b-6d59-46cc-9e4e-5ff2e6f54b7e)

**Comment by Nikita-Zaitsev-ML** [comment]
для данных логичнее использовать `type` вместо `interface`.

И незачем добавить приставку `AirDatepicker`: мы и так в этом модуле 
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/fd005d34-1f8f-4e75-b83f-9e3d1638594a)

**Comment by Nikita-Zaitsev-ML** [comment]
Опции все-таки лучше вынести из метода инициализации т.к. хоть они и ближе к месту использования, но обычно их требуется корректировать и удобнее это делать когда они на более видном месте

![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/05ee8d92-93ce-4e7a-a1e3-d8e4b77e130a)
![image](https://github.com/Alexioi/toxin-hotel/assets/104826556/b0ac22bc-18a3-4a27-97d8-19f92c29c7e2)

**Comment by Nikita-Zaitsev-ML** [comment]
https://github.com/Alexioi/toxin-hotel/issues/5#issuecomment-1627066821

над этим можно еще поработать
![Code_svMVJlieMw](https://github.com/Alexioi/toxin-hotel/assets/104826556/8fbbc7a7-5eb1-40e5-902b-142f1dd0b5a0)

**Comment by Nikita-Zaitsev-ML** [comment]
https://github.com/Alexioi/toxin-hotel/issues/5#issuecomment-1627098400

![Code_sd38G8T7en](https://github.com/Alexioi/toxin-hotel/assets/104826556/9067e31e-e657-40dd-a199-671f10cb6d0b)
